### ISSUE TITLE
Add-on not starting after installation.

### ISSUE THREAD

**Issue by samuelrajan747** [hassio-addons/addon-thelounge#182]
# Problem/Motivation

> The add-on is crashing upon starting for the first time post installation

## Expected behavior

> The usual happy path

## Actual behavior

> I guess the screenshots attached below should help, please give me a shout if more info is needed to debug this. My doubt is that the installer has missed copying over some necessary files, but that just a hunch.
![image](https://github.com/hassio-addons/addon-thelounge/assets/23404138/bb0b8bad-47bc-40c4-83d9-c4b0f2961655)
![image](https://github.com/hassio-addons/addon-thelounge/assets/23404138/271a09dc-b674-48e9-9143-4aa25c57ca0a)
![image](https://github.com/hassio-addons/addon-thelounge/assets/23404138/ada815f9-217c-489c-8c82-37be372979ef)
![image](https://github.com/hassio-addons/addon-thelounge/assets/23404138/188579ff-8bd0-484d-8882-5ccc968d0ade)

## Steps to reproduce

> I guess, if someone runs with the same HA and addon version as mine this should happen.

## Proposed changes

> Sorry
> No clues

Thanks in advance.

**Comment by sinclairpaul** [comment]
As per the log entry, please configure the `users` option - <https://github.com/hassio-addons/addon-thelounge/blob/main/thelounge/DOCS.md#option-users>

**Comment by samuelrajan747** [comment]
Thanks, I thought about that, but couldn't find examples in any public config repo. Can you please point me in the right direction, Attached below the config that I created :(.

![image](https://github.com/hassio-addons/addon-thelounge/assets/23404138/ccac1c73-4802-43f5-8526-23ee90506863)

**Comment by sinclairpaul** [comment]
Addons aren't managed by Home Assistant Configuration, they are separate pieces of software.

Please select the Configuration tab and enter it there.

![image](https://github.com/hassio-addons/addon-thelounge/assets/24625998/48a65b64-aa65-4a60-aafc-c7b8c01e2d52)

**Comment by samuelrajan747** [comment]
Thanks a lot, You made my day.
Happy New Year.

Thanks again.
