### ISSUE TITLE
User Configuration

### ISSUE THREAD

**Issue by nickdaria** [hassio-addons/addon-thelounge#5]
I have been loving this addon and I moved all of my settings over, however I host The Lounge for me and a few others and normally these accounts are configured using a users folder with JSON files, and you would point the container folder to a host folder for configuration. Is this possible with the hassio addon? If so, where is the linked folder on the host filesystem?

Thanks.

**Comment by timmo001** [comment]
This is currently not possible. Currently, there is one user created which is the only one avaliable.

This can most likely be added. Thanks for bringing this up!

**Comment by nickdaria** [comment]
> This is currently not possible. Currently, there is one user created which is the only one avaliable.
> 
> This can most likely be added. Thanks for bringing this up!

No problem! Do you have any insight as to how container -> host file system links are handled in hass.io? I would gladly set this type of configuration up and maybe even write a quick python script to create users from hassio addon configuration. 

In regular docker containers, you simply configure the config directory in the container to a directory on the host using Docker-compose/Docker-cli, or Portainer. The problem is that hass.io sandboxes addons so the Portainer addon cannot access the hassio addon containers, just the images.

**Comment by timmo001** [comment]
It's a little more complex than the typical docker volume mapping. If you are interested, take a look at the hassio docs:

https://developers.home-assistant.io/docs/en/hassio_addon_index.html
