### ISSUE TITLE
Addon refuses to start after power outage (not clean shutdown)

### ISSUE THREAD

**Issue by pasiz** [hassio-addons/addon-thelounge#78]
# Problem/Motivation
Addon refuses to start

> (Why the issue was filed)
This happened few times, after power outage

## Expected behavior
Addon should start

> (What you expected to happen)

## Actual behavior
Addon doesn't start

> (What actually happened)

## Steps to reproduce
Power outage, and after that, addon cannot started

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

here is the log:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: The Lounge
 A self-hosted web IRC client
-----------------------------------------------------------
 Add-on version: 0.12.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (amd64 / qemux86-64)
 Home Assistant Core: 2021.8.6
 Home Assistant Supervisor: 2021.06.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] thelounge.sh: executing... 
2021-08-15 12:31:41 [WARN] You are currently running The Lounge as root. We highly discourage running as root!
2021-08-15 12:31:48 [INFO] Users:
2021-08-15 12:31:48 [INFO] 1. xxxxx
2021-08-15 12:31:48 [WARN] You are currently running The Lounge as root. We highly discourage running as root!
2021-08-15 12:31:49 [INFO] Retrieving information about the package...
2021-08-15 12:31:50 [ERROR] TypeError: Cannot read property 'latest' of undefined
[cont-init.d] thelounge.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by pasiz** [comment]
even partial backup doesn't help, need to reinstall whole addon

**Comment by sinclairpaul** [comment]
There was an issue with the default theme being unavailable, this was changed in the latest release, however it won't impact existing config.

You can change it by setting it to "thelounge-theme-solarized" rather than "thelounge-theme-material"

**Comment by pasiz** [comment]
it does it after i install clean latest version too. I try the theme...

**Comment by pasiz** [comment]
i have only "Morning" and "Default" on theme selection...

**Comment by Narmoistar** [comment]
I am having this same issue after updating to the latest version.

**Comment by pasiz** [comment]
Yes, can confirm it's the theme. Should the config parser be more informative than 'Cannot read property 'latest' of undefined'

**Comment by sha1sum** [comment]
Same thing happened to me here, and the same solution worked. In my case I had to remove excess `themes` entries from the configuration as well as change the `default_theme` so that the only reference that remained was `thelounge-theme-solarized`.

**Comment by frenck** [comment]
> Yes, can confirm it's the theme. Should the config parser be more informative than 'Cannot read property 'latest' of undefined'

I agree this is not in control of the add-on, this message is thrown by The Lounge itself,
see: <https://github.com/hassio-addons/addon-thelounge/blob/main/thelounge/rootfs/etc/cont-init.d/thelounge.sh#L50>

Therefore not a problem the add-on should solve.
